### ISSUE TITLE
分包 从主包跳转副包 报错

### ISSUE THREAD

**Issue by zhuweilong** [jypblue/wmp-starter#3]
Cannot read property 'webpackJsonp' of undefined
TypeError: Cannot read property 'webpackJsonp' of undefined

**Comment by jypblue** [comment]
贴一下报错信息吧

**Comment by jypblue** [comment]
类似于这样就可以了
![image](https://user-images.githubusercontent.com/5317786/88470942-4a00bc80-cf35-11ea-93e6-72b62d250836.png)
